### ISSUE TITLE
FGTpartitioner.py -h fails

### ISSUE THREAD

**Issue by dangeles** [tkchafin/FGTpartitioner#2]
https://github.com/openjournals/joss-reviews/issues/2030

I followed the setup instructions on the README. Installation seemingly went flawlessly. When I typed:

`./FGTpartitioner.py -h`

I get the following error when using python 3.7.6:
```
  File "./FGTpartitioner.py", line 73
    print("Diploid resolution strategy: ", end="")
                                              ^
SyntaxError: invalid syntax
```

However, `python FGTpartitioner.py -h` works. I think the header in the script is wrong---it should be `#!/usr/bin/env`, not `#!/usr/bin/python`.

**Comment by tkchafin** [comment]
Fixed in latest commit- although depends on the location of your python install (e.g. still fails for me since my Python is in ~/anaconda3/bin). Code now correctly points to the default system python though, and I added a note in the README
